import HelloWorldButton from './components/hello-world-button/hello-world-button';
import Heading from './components/heading/heading';
import _ from 'lodash';
// import addImage from './add-image';
const heading = new Heading();
heading.render(_.upperFirst('hello world'));
const hwButton = new HelloWorldButton();
hwButton.render();
const ten = '11';
// addImage();